"""Add duration field to PauseLog

Revision ID: 10f1e0cf63df
Revises: 24a9cb622ec7
Create Date: 2025-10-14 13:29:52.233078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f1e0cf63df'
down_revision = '24a9cb622ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pause_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pause_log', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
