"""Add accepted and status_message fields to Job

Revision ID: 24a9cb622ec7
Revises: f7ba16ac1106
Create Date: 2025-10-09 11:31:16.867519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a9cb622ec7'
down_revision = 'f7ba16ac1106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_message', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('status_message')

    # ### end Alembic commands ###
