"""Add accepted field to Job model

Revision ID: f7ba16ac1106
Revises: 2d4f8a8e361e
Create Date: 2025-10-09 11:16:51.745309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ba16ac1106'
down_revision = '2d4f8a8e361e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('technician')
    op.drop_table('jobs_done')
    op.drop_table('shift_log')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('accepted')

    op.create_table('shift_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('technician_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('start_time', sa.TIME(), nullable=True),
    sa.Column('end_time', sa.TIME(), nullable=True),
    sa.ForeignKeyConstraint(['technician_id'], ['technician.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs_done',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('start_time', sa.DATETIME(), nullable=True),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('total_work_duration', sa.INTEGER(), nullable=True),
    sa.Column('vehicle_registration', sa.VARCHAR(length=50), nullable=True),
    sa.Column('vehicle_model', sa.VARCHAR(length=100), nullable=True),
    sa.Column('vehicle_year', sa.VARCHAR(length=4), nullable=True),
    sa.Column('vehicle_color', sa.VARCHAR(length=50), nullable=True),
    sa.Column('total_cost', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('technician_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('pause_summary', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technician',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), nullable=True),
    sa.Column('specialization', sa.VARCHAR(length=150), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
